language: java
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean test jacoco:report
after_success:
  - mvn coveralls:report
jdk:
  - openjdk7
  - oraclejdk8